branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
before_script: 
  # Set read-write git origin
  - git remote set-url origin $REPO.git
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set deployment target to github pages
  - rake setup_github_pages[$REPO]
script:
  # Generate site
  - rake generate
after_script:
  # Workaround for travis not to try run rake on generated site
  - ! 'echo ''script: "ls *.html"'' > public/.travis.yml'
  # Deploy!
  - rake deploy
env:
  global:
    # Repo read-write address
    - REPO="git@github.com:floydpink/harimenon.com"
    # SSH key. Encoded. See https://gist.github.com/4242707
    - secure: "gzAGrp9JzRSxhfZMCbqsdA8vFOJgy4ASs8PnJcV7+3djyN3sYmcoqGC6YCRP\nnDKIGD+aqPmRpfXdl0flUIdzSTJXmKa+vEl4NRHn21JLPlKWTyNuA16Tjrh0\nxxDD/lFy0FbqUmpsdzo574SmOPu8xHy6Y2o10UcLw02yA8yDFYY="
    - secure: "fOng6h3hcQTYMcDKPFHpRLLDymc6jYk4Q6U26jha+uTV8x9K7QSDadEobIwI\namtNO78OYpDzr1Fmgufc2+Mdco/lNsPcWNo2RmyL6pA6tiut8rNJ4ChXYV/D\nZ/+/LQTZEGbdeZ22AuSaDx9o/HEEQkxU7aYNKwLYVTnDmfouJzk="
    - secure: "Vk4Vgff+Z9U+7CEB+ooMqZyWfhdz/X5C9gdB2dpiJWrpCRvXHM06CsfGvZTp\n1tuxYhRL2mV+BIGggSKbzdHmhFr0OcpkN/HI1Hn1OVhnqOswKF95K4g4bHln\n9ZZprgwQNdBJlYN6oo5/oa+70ApdRrrYBzBSA/gNv/RkK64SueI="
    - secure: "AP2GrsfFkulp658eIEeM5NuXcuyV1gQVrnJDyQ86ZYW4K/I6AGxOF9ULOg28\nrZLCTH6wYcQVOR6y8FraRWjgMGk09CvOVI6mswCB57xvOrpedz8QNtnuKI0T\nItepOpfZSWT8pEqr3Y/pcvvHemsGVhcoHkEZRNFQEHIq6YbKEEo="
    - secure: "ElvvR6L0mtyeDn909+/Ph8kALmqn5K4jHA/mNLam5fyvFjjdY8U/zRRnKf5H\nTYVq5kNIEIKbxGhL9AVkvAaSkFXaflvaq/26IhdQ6+ein3pTeaaSHNftiLUD\nhSdqFoNHfgyvyeaIjuXZrhAoLH3Su1TvW5ceS9L/gqqWQXOVdvE="
    - secure: "ex0ZQRDo3xTWpEajRE/WOcy7u+m+AKtpyXd3WTokO8e5u2KxhVhwNyqifBge\nfm4zG/yyFKaRCZva3YdOAp4QmQIpmZ8dMOwewHjdT/2kbjJxTaGh/B4xE/xh\nf5gVAuxZOfwBMdFgEMjBDvhAQxoAd4AG+yIk4yBJiq/m+m4l2xs="
    - secure: "fyY52D1/FChrVJdl5btInkXnVOfb3q7QHhKpCn0yvVJCt3H4iu3EJN39u1Fh\n9ieI9DUDl71jrz4SUVa84lbk+aI8b/DrFUeMQb18jizyqqY8wigqmAyWMrl8\nV4obEehc0mATFq2E++doEvgaZdRebacihLAeDaBqLRFEh5QviM0="
    - secure: "Ft/NmCY5nVDncawwStxScRj3bhCfmwrEF3B3EwkPsICIMiBtIUpbHt8F4xrs\nCVIhlJf8fhnip/Byc2POIBV1DDjhYn7DO40es9s9rKlrYTwi3812vTxWVioY\nF1wkXJxA/Orvv5PwJ5n0/cjPVu2TUhBdcnoxofNU+08SZ1e6JvU="
    - secure: "FRwtIcjGm87zNmsiNlP8wtTtCaVbUi0YdwU3BJ9aB1JkS7qexK83hdMrtdY2\nAvJV0/YK+POy3EM0RR7QK+dbT5BpynviY/m4EKVTwMvpim17fwZYjPJUPXky\nM2rMgbwE9QlZYeO/XlS+ePM08ZLEtu368SNbvofeL2Ai5eIatLo="
    - secure: "RhTGTSsVVOr6muDSxY3XfY/kEqdG9jQM5shfqNbHdHvKozKJ4/pvX7NrrXD1\n4h6BTBf/HiJYVbmEyiwD3Y60nkloBy2bkxyowJZ1vlQrLk6LQzXLZLd4SPfq\nWbGKEhniBuMQ4THmDq+Tm94m2PdwbNLmaUnSeibNatj2znKNr8w="
    - secure: "agLiyZqy2RPyj6mqfYKDbmWoMT2ShGZGKKUESl9vO7EZCTCp2dAjxWQcSrcB\nCZPUqbShvw1NVx2VGr/UuXuxcCPryNTbtdhBU7oZNRKxhsQLGa4irne1OtgA\nAc45EXq4bSeNzHyKQ8Xdr8acIHC9nRqFrjdJR1nopmr5wcgAuG4="
    - secure: "O4x7Imm9NO6oZIFmdhcFEC3ITLa6vcrjmAI9N9cT8+gY7+YAqUNWPeoP40//\nFFuiD3ST3F7XVUzoqr20CujvEfI/KYwxOZFjOymG+99eAH+dT6Waz5Fum1WB\nf7ide0WEr5mj33YnqDpXNtYycM4qAtKYv3SkVQfiiBsVs+C2yks="
    - secure: "ikkRgSqdt3jXYif8RznKGCltVEVxDml2TWuYglgaMOhRg4HLV74JNwAkfzLy\nU7ZDErejgzaZ/4Df3tAJB3GTU4qS8RRfkwhSVxPOs1DjTLMuye8vDfs/O0gt\nQ5Gfxe7+v/ryx4pklh3EeRJqDtX4Ez5G+xkY8ul7JRDXs69t9go="
    - secure: "e7z1JqST9QKgzpuovFKzWcZn7mKKQy3gjh3on1DX+4w6DpeZYLIWV5ie9K2l\n3FIhQeRjJuVQdIoVhTd8pn/0CpvurPBuY5ImeB3449fiAiCIclxljVY6BR1N\no9uQPt4T1s9V2cnY4KF7IzODZ1Xg2Y5gwqAJdKXBwCifHf33H40="
    - secure: "iQHqenY41wYX6Z1Hmiv1H4kXBfFyvJhLnG14P0Je2BVwZSE7YJFiXx+t1aEf\nkb4x7xfGZTNsjfsuWNXGu/WnH3ItqNVjVCGbgDWSBD2hvfWCYW8y5lvphZwZ\nV6XDzBBkkvm3fzK7RtZX+y50th+mbi8Q9I1xxlcYSudwAIQNwEg="
    - secure: "Tm3fFAxEeiWbORsHD6FOBBLof6XPZt23FElmqOaCLwZLB8YlK39HkESuLTNN\nA9kMD/31Mat9SaYeVuDB2ydDEXaqzB5oigTL5djPVYd2myRpVCUTvziOLp/o\n+qlJ5SngJIqCTmr7356XLL5OzMeyUxMKL8YP17u0G0pi7ZhoY+Y="
    - secure: "F14ttA7ZhLoPfyul4sm3+Jk3nC6Q3Nr+Ky5w6TjamAjFNgijNBpnfJ5xrYA+\n2X+8AQFbwSq7RmMvtLruX7L7AHHbcDu8A0JpXpxvTJoBHcAM7pQ2MARKdtcP\noFKWKS0HBPC0aXT77AV39gWpIJ0Nup2gou8/gwyC9eQoGyWq7M0="
    - secure: "IS3H/HowoSTymlrE9gfmJICGJvPtXdgbGM9ugdt3/MpI5KPur6+XcU4zmh4H\n3PqKlL1ec6MURnlcbug58pdYxwdZoNYeA6URibMRRTGYLMRuEHm2vVsDrZV/\ncc1ffQCCOmdygSzVsokMqlHJyOm3ulI1/lsF4C6wAWaHYRUndFk="
    - secure: "ZxpPofnxhuP9lZ2V5Pm3PK69y7078nPNuNfyBZjJQQ/BuDEILVpF19O/4n7n\nKi8DxQlZdNu/0PjVyzBJ1QcuCVPZ89TjJUa8B7Rvgor3sCrEeon8he2lnPW2\nVyRKg/dAb4t7ogEKzRXLn4E30ZjcjSGj0fc92P3sA/iTV1s7hnw="
    - secure: "ak0/Hr5bpn2HjGg/eNuEorfMSrbJK3sfgvDb5slOL7mjB3P88aOLFJn5tqQq\nvWUBPkpxj0p0NB4vJFP5bUhOAan+TBhlBYcqqkzgm/SepzV/1coT1iHx7ram\n/3U0HrUY1NKM8oWW8xvoFj+hr/ucZfKv3P9gAOoTyKijsKTyYKc="
    - secure: "WwBc5nN/OioxjI7xJw3YH4xn2+6bcx4nj478N7NfhgIia7A6jQ9fZfmKRMbv\nQjA1gcyRMnlJdI5h+cnsbXBHbf++wEHZwbDvbAOzo8ltZYmJmt92xIH/S8/G\nJ6ulp4wGOfzFRdPu0UFPPZAk8U01CUAZDYSRjDuFef+a0qwFVWg="
    - secure: "QDovyrhOxyLjxcqFvgyH+ji8s/gLFyIp0sUMsYI6bFyEpd5LF9du2vKR1m71\n9WftJFXS8BL93K17bxyzmhBm2jDv0W8rVCu3595iADsJ049sUmuosjLkGhXf\n22yATFXK4HoSK3OrsoEZZwaVAj36g1qyqOtHFupbvPHnOsjA/4M="
    - secure: "M1z1q6OdgIoUP0lPaAnWf+c7mexPRSRwuzqB7jS4eyLorrgCwqw26ottCRpG\nijksGzo54Lful8LmVguORzXiHz8FP9p/WPEuZ5hktnYZbZxPPmDFHosThkM3\n9Zo3vve1O8r7YwBFs8C6iLjj9WScD7GirhiE4fyk0wsZXUUi+l8="

