language: node_js
node_js:
  - 14
cache:
  yarn: false
  directories:
    - node_modules
os:
- osx
branches:
  only:
  - master
before_install:
- export TZ=America/New_York
- date
- npm install -g hexo
install:
- npm install
before_script:
- git config --global user.name "Floyd Pink (via Travis-CI)"
- git config --global user.email "imbleedingme@googlemail.com"
script:
- hexo generate
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m "Site updated at $(date +'%Y-%m-%d_%H-%M-%S')"
- git branch -m gh-pages
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push -q -u origin gh-pages; fi
