version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.18
    environment:
      TZ: "America/New_York"
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate blog
          command: hexo generate -b
      - persist_to_workspace:
          root: public
          paths:
            - "*"
  deploy:
    docker:
      - image: cimg/node:20.18
    environment:
      TZ: "America/New_York"
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - "ab:00:27:bf:df:bc:56:8e:9d:d1:bc:09:2e:62:c0:a9"
      - deploy:
          name: Deploy website
          command: |
            git config --global user.name "Floyd Pink (via Circle CI)"
            git config --global user.email "imbleedingme@googlemail.com"
            sh deploy.sh
  verify:
    docker:
      - image: cimg/node:20.18
    steps:
      - run:
          name: Install BLC
          command: sudo npm install -g broken-link-checker
      - run:
          name: Check broken internal links
          command: blc https://harimenon.com -roe

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
      - verify:
          requires:
            - deploy
