# Header
logo_text: Home
menu:
  About: about
  Blog: archives
  Tags: tags
  Rss: /atom.xml

# Content
excerpt_link: Read More
toc: false #  Whether to show the table of contents in articles
fancybox: true

# Miscellaneous
google_analytics: UA-4869398-4
favicon: /favicon.png

# Share
share_jia: false
share_addthis: true